# Generated by Django 4.1.4 on 2022-12-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
